name: arcas-hla
channels:
- bioconda
dependencies:
- bedtools==2.26.0
- kallisto==0.44.0
- pip==23.3.1
- python==3.10.0
- samtools==1.11
- pip:
  - biopython==1.83
  - numpy==1.26.3
  - pandas==2.2.0
  - pytest==8.0.0
  - scipy==1.12.0
