name: Docker build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      run: docker build -t test-arcas-hla -f Docker/Dockerfile .
    - name: Test with pytest
      run: docker run --rm -v $GITHUB_WORKSPACE:/home test-arcas-hla pytest
